### ISSUE TITLE
Render time series at the correct location

### ISSUE THREAD

**Issue by bruno-garcia** [NuGetTrends/nuget-trends#26]
Looking at this: https://beta.nugettrends.com/packages?months=75&ids=Aardvark.Base.FSharp&ids=Aardvark.Base&ids=AdRotator&ids=Sentry

Sentry which was published 6 months ago is shown in the beginning of the graph which is 6 years ago.

**Comment by joaopgrassi** [comment]
The issue is caused because we plot the chart with the dates we have. If we have a package with data for the whole period and another which only has from the middle onwards, chartjs plots it at the beginning. To "fix" it, we have to specifically return 0 or null for the months/days/weeks of data, so the dataset is the same for each package. 

Here's a demo of the issue (see how North America starts at the beginning)
https://stackblitz.com/edit/angular-h83adp-chartjs-wbud3g

Here's the same chart "fixed" 
https://stackblitz.com/edit/angular-h83adp-chartjs-jtf6lq
